version: "2"
services:
    booking-saas-db:
      image: mysql:5.7
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
      ports:
        - "9906:3306"

    booking-saas-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: booking-saas-phpmyadmin
        links:
            - booking-saas-db:db
        ports:
            - 8000:80
volumes:
    persistent: